# -*- coding: utf-8 -*-
"""Decreasing 224x224 mix_data_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17QocLz2nJRRS1sXgHqD1K5wHDCPEoQhk
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.image import imread
import tensorflow as tf
import cv2
import random

from google.colab import drive
drive.mount('/content/drive')

data_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/RXT nosso'
dest_dir = '/content/drive/My Drive/Colab Notebooks/Mestrado final/RXT 224x224 mix_data_2'

"""Reducing the size of images from the HCFMRP database to 224x224 pixels"""

def diminui_224x224_nl (dir_origem, dir_destino, class_dir_name):

  images_names = tf.io.gfile.listdir(dir_origem+'/'+class_dir_name)

  for i in images_names:
    img = cv2.imread(dir_origem+'/'+class_dir_name+'/'+i)
    img = cv2.resize(img, (224, 224))
    cv2.imwrite(dir_destino+'/'+class_dir_name+'/'+i, img)

  print(len(tf.io.gfile.listdir(dir_origem+'/'+class_dir_name)))
  print(len(tf.io.gfile.listdir(dir_destino+'/'+class_dir_name)))

diminui_224x224_nl(data_dir,dest_dir,'covid')

diminui_224x224_nl(data_dir,dest_dir,'dip')

diminui_224x224_nl(data_dir,dest_dir,'normais')

diminui_224x224_nl(data_dir,dest_dir,'tuberculose')

data_dir_novo_covid = '/content/drive/My Drive/Colab Notebooks/Mestrado final/Curated X-Ray Dataset COVID/covid'

data_dir_novo_normais = '/content/drive/My Drive/Colab Notebooks/Mestrado final/Curated X-Ray Dataset normais/normais'

data_dir_novo_tuberculose = '/content/drive/My Drive/Colab Notebooks/Mestrado final/Mont-Shen Dataset TB'

"""Reducing the size of the images, collect a percentage of the total images, to choose randomly."""

def diminui_224x224_mix_data_novo (dir_origem, dir_destino, novo_perc):

  images_names = tf.io.gfile.listdir(dir_origem)

  cut_point = np.around(len(images_names)*novo_perc).astype(int)

  random.shuffle(images_names)

  images = images_names[:cut_point]

  for i in images:
    img = cv2.imread(dir_origem+'/'+i)
    img = cv2.resize(img, (224, 224))
    cv2.imwrite(dir_destino+'/'+'N'+i, img)

  print(len(tf.io.gfile.listdir(dir_origem)))
  print(len(tf.io.gfile.listdir(dir_destino)))

diminui_224x224_mix_data_novo(data_dir_novo_covid,dest_dir+'/covid',0.289)

diminui_224x224_mix_data_novo(data_dir_novo_normais,dest_dir+'/normais',0.054)

diminui_224x224_mix_data_novo(data_dir_novo_tuberculose,dest_dir+'/tuberculose',1.0)